version: '2.1'

services:

  users-db:
    container_name: users-db
    build: ./services/users/src/db
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0
  
  posts-db:
    container_name: posts-db
    build: ./services/posts/src/db
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  posts-storage:
    container_name: posts-storage
    build: ./services/posts/storage/
    volumes:
      - './services/posts/storage:/usr/src/app'
      - './services/posts/storage/package.json:/usr/src/package.json'
      - './services/posts/storage/node_modules:/usr/src/node_modules'
    ports:
      - '3003:3003'
    environment:
      - NODE_ENV=${NODE_ENV}

  users-service:
    container_name: users-service
    build: ./services/users/
    volumes:
      - './services/users:/usr/src/app'
      - './services/users/package.json:/usr/src/package.json'
      - './services/users/node_modules:/usr/src/node_modules'
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - NODE_ENV=${NODE_ENV}
      - TOKEN_SECRET=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe'\xab\xa6L6\xdd\x8d[\xccO\xfe
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db

  posts-service:
    container_name: posts-service
    build: ./services/posts/
    volumes:
      - './services/posts:/usr/src/app'
      - './services/posts/package.json:/usr/src/package.json'
      - './services/posts/node_modules:/usr/src/node_modules'
    ports:
      - '3002:3002'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@posts-db:5432/posts_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@posts-db:5432/posts_test
      - NODE_ENV=${NODE_ENV}
      - TOKEN_SECRET=\x02\xf3\xf7r\t\x9f\xee\xbbu\xb1\xe1\x90\xfe'\xab\xa6L6\xdd\x8d[\xccO\xfe
    depends_on:
      posts-db:
        condition: service_healthy
      posts-storage:
        condition: service_started
      users-service:
        condition: service_started
    links:
      - posts-db
      - posts-storage
      - users-service

  web-service:
    container_name: web-service
    build: ./services/web/
    volumes:
      - './services/web:/usr/src/app'
      - './services/web/package.json:/usr/src/package.json'
      - './services/web/node_modules:/usr/src/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      users-service:
        condition: service_started
      posts-service:
        condition: service_started
    links:
      - users-service
      - posts-service

  swagger:
    container_name: swagger
    build: ./services/posts/swagger/
    volumes:
      - './services/posts/swagger:/usr/src/app'
      - './services/posts/swagger/package.json:/usr/src/package.json'
      - './services/posts/swagger/node_modules:/usr/src/node_modules'
    ports:
      - '3004:3004'
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      users-service:
        condition: service_started
      posts-service:
        condition: service_started
    links:
      - users-service
      - posts-service