---
swagger: "2.0"
info:
  description: "Restpublica Posts API Swagger"
  version: "0.0.1"
  title: "Restpublica Posts API"
host: "localhost:3008"
basePath: "/posts"
schemes:
  - "http"
produces:
  - "text/html"
  - "application/json"
paths:
  /ping:
    get:
      summary: Sanity check
      description: Sanity check
      responses:
        200:
          description: 'pong'
